# Generated by Django 5.2.3 on 2025-06-14 09:49

import pgvector.django.vector
from django.db import migrations, models
from pgvector.django import VectorExtension # 追加


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        VectorExtension(), # 追加
        migrations.CreateModel(
            name='DataTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chunks', models.TextField(blank=True, null=True)),
                ('embeddings', pgvector.django.vector.VectorField(dimensions=1536)),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'data_tabel',
            },
        ),
    ]
